# Publish the demo application for the "carbon-react-web-component-integration" branch
name: Publish feature branch demo

# This workflow is triggered by every push into the "carbon-react-web-component-integration" branch
on:
  push:
    branches: [ carbon-react-web-components-integration ]

jobs:
  publish-cdn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: "0"
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
      - name: Install dependencies
        run: |
          npm install
          npm run build
      # ie. https://chat.carbondesignsystem.com/feature/demo/index.html
      - name: Upload demo to COS
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.COMMON_COS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COMMON_COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COMMON_COS_ENDPOINT }}
          SOURCE_DIR: "demo/dist"
          DEST_DIR: "feature/demo"